services:
  php-fpm:
    build: .
    container_name: php-webserver
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /opt/deploy/data/web_root:/var/www/html
    networks:
      - deploy-network
    deploy:
      resources:
        limits:
          memory: ${PHP_MEMORY_LIMIT:-256M}

networks:
  deploy-network:
    external: true
