services:
  sftp:
    image: emberstack/sftp:latest
    container_name: sftp-server
    restart: always
    ports:
      - "2222:22"
    volumes:
      - /opt/deploy/data/web_root:/home/webuser/web_root
      - /opt/deploy/data/ftp_storage:/home/filesuser/my_ftp_files
      - /opt/deploy/storage/sftp.json:/app/config/sftp.json:ro
    networks:
      - deploy-network
    deploy:
      resources:
        limits:
          memory: 128M

networks:
  deploy-network:
    external: true
